### ISSUE TITLE
contribution guidelines

### ISSUE THREAD

**Issue by noraj** [immunIT/drupwn#27]
based on #22 and #23 you should create a `CONTRIBUTING.md` or similar file to explain contribution guidelines like making PR in develop branch, etc.

I wrote ~~an overkill~~ one for one of my projects: https://inventory.rawsec.ml/docs/docs/en/add.html

**Comment by immunIT** [comment]
Fixed #28

**Comment by noraj** [comment]
https://github.com/immunIT/drupwn/blob/master/CONTRIBUTING.md
