### ISSUE TITLE
Bug in module detection

### ISSUE THREAD

**Issue by falsovsky** [immunIT/drupwn#3]
Hi, 

While logging the requests to my webserver I saw that theres something wrong with the "modules" detection. A slash is missing on the url.

Example request being made:

> GET /sites/default/modulesrestws_views/restws_views.module

There is a / missing after "modules".

You need to edit this line:
https://github.com/immunIT/drupwn/blob/master/plugins/Modules.py#L22

And probably add a slash after the path.

Thanks for your work, this is pretty nice!

**Comment by immunIT** [comment]
Well spotted. I'm on it.
